version: '3'
services:
  blockchain-load-monitoring-service:
    container_name: blockchain-load-monitoring-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    volumes:
      - ./logs:/app/logs
