version: '3'
services:
  mainnet-monitoring-service:
    container_name: "mainnet-blockchain-load-monitoring-service"
    image: "mainnet-blockchain-load-monitoring-service:01"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: mainnet.env
    restart: on-failure
    volumes:
      - ./logs_mainnet:/app/logs_mainnet

  testnet-monitoring-service:
    container_name: "testnet-blockchain-load-monitoring-service"
    image: "testnet-blockchain-load-monitoring-service:01"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: testnet.env
    restart: on-failure
    volumes:
      - ./logs_testnet:/app/logs_testnet
