version: '3'
services:
  blockchain-load-monitoring-service:
    container_name: ${NETWORK}-blockchain-load-monitoring-service:01
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    volumes:
      - ./logs:/app/logs
